# Generated by Django 3.0.7 on 2020-06-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.TextField(default=None)),
                ('file', models.FileField(upload_to='Posts')),
                ('content', models.TextField(default=None)),
                ('upvotes', models.IntegerField(default=0)),
            ],
        ),
    ]
