# Generated by Django 3.0.5 on 2020-05-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_doctor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.FileField(default='default.jpg', upload_to='med_report'),
        ),
    ]
