# Generated by Django 3.0.5 on 2020-05-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20200523_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='approve',
            field=models.CharField(default='Not Approved', max_length=20),
        ),
    ]
